# Generated by Django 4.0.3 on 2022-04-10 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_todo_owner_trip_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='photo',
            field=models.ImageField(blank=True, default='images/default.jpg', upload_to='images/'),
        ),
    ]
