# Generated by Django 4.0.3 on 2022-04-12 22:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('trips', '0004_tripmember'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='members',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='TripMember',
        ),
    ]
