# Generated by Django 4.0.4 on 2022-04-14 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0005_trip_members_delete_tripmember'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='summary',
        ),
    ]
